// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxisImporter;

#nullable disable

namespace TaxisImporter.Migrations
{
    [DbContext(typeof(TaxiDbContext))]
    partial class TaxiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaxisImporter.Models.Taxis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("colour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("distance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("dropoff")
                        .HasColumnType("datetime2");

                    b.Property<string>("dropoffZone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dropoff_borough")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("fare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("passengers")
                        .HasColumnType("int");

                    b.Property<string>("payment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("pickup")
                        .HasColumnType("datetime2");

                    b.Property<string>("pickupZone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pickup_borough")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("tip")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("toll")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("total")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Taxis");
                });
#pragma warning restore 612, 618
        }
    }
}
